const books2024 = [
  {
    id: 1,
    bookTitle: "Genghis Khan and the Making of the Modern World",
    author: "Jack Weatherford",
  },
  { id: 2, bookTitle: "The Da Vinci Code", author: "Dan Brown" },
  { id: 3, bookTitle: "The Lost Symbol", author: "Dan Brown" },
  { id: 4, bookTitle: "Inferno", author: "Dan Brown" },
  { id: 5, bookTitle: "Girl on the Run", author: "Jane Costello" },
  { id: 6, bookTitle: "Reckless Series (3 books)", author: "Gina Robinson" },
  { id: 7, bookTitle: "Ruthless Hawke", author: "Gwyn McNamee" },
  { id: 8, bookTitle: "Passion and Privilege", author: "Lexy Timms" },
  { id: 9, bookTitle: "Lone Star Princess", author: "Lenora Worth" },
  { id: 10, bookTitle: "Imperfect Chemistry", author: "Mary Frame" },
  { id: 11, bookTitle: "Blue Moon", author: "Lori Handleland" },
  { id: 12, bookTitle: "The Alpha's Saviour", author: "Reece Barden" },
  { id: 13, bookTitle: "Hostile Hearts", author: "K E Osborn" },
  { id: 14, bookTitle: "Surging Tide", author: "Lexy Timms" },
  { id: 15, bookTitle: "The Cupcake Cottage", author: "Jean Oram" },
  { id: 16, bookTitle: "The Cowboy Next Door", author: "Trish Milburn" },
  { id: 17, bookTitle: "The Institution", author: "Helen Fields" },
  { id: 18, bookTitle: "The Roommate", author: "Lexy Timms" },
  { id: 19, bookTitle: "The Mystery Guest", author: "Nita Prose" },
  { id: 20, bookTitle: "Perfect Stranger", author: "Lexy Timms" },
  { id: 21, bookTitle: "Never Lie", author: "Freida McFadden" },
  {
    id: 22,
    bookTitle: "Talking with Serial Killers",
    author: "Christopher Berry-Dee",
  },
  { id: 23, bookTitle: "One by One", author: "Freida McFadden" },
  { id: 24, bookTitle: "Ward D", author: "Freida McFadden" },
  { id: 25, bookTitle: "The Teacher", author: "Freida McFadden" },
  { id: 26, bookTitle: "The Coworker", author: "Freida McFadden" },
  { id: 27, bookTitle: "The Inmate", author: "Freida McFadden" },
  { id: 28, bookTitle: "The Locked Door", author: "Freida McFadden" },
  { id: 29, bookTitle: "The Last Flight", author: "Julie Clark" },
  { id: 30, bookTitle: "A Court of Thorns and Roses", author: "Sarah J. Maas" },
  { id: 31, bookTitle: "A Court of Mist and Fury", author: "Sarah J. Maas" },
  { id: 32, bookTitle: "A Court of Wings and Ruin", author: "Sarah J. Maas" },
];

export default books2024;
